services:
  headscale:
    image: headscale/headscale:latest
    volumes:
      - ./config:/etc/headscale
      - headscale-data:/var/lib/headscale
    ports:
      - 8080:8080  # 容器內聽 8080，Zeabur 會自動對外對應
    command: headscale serve
    restart: always

volumes:
  headscale-data: